### ISSUE TITLE
Errot after updating to latest Docker

### ISSUE THREAD

**Issue by ExXxtr3me2** [revenz/Fenrus#14]
After the update this morning, i´m getting this error:

TypeError: /app/views/home.ejs:28
    26|                     partialFile = `./partials/dashboard/${type.toLowerCase()}.ejs`;
    27|                 %>
 >> 28|                 <%- include(partialFile, itemModel ) %>
    29|                 <%
    30|             }
    31|         }

/app/views/partials/dashboard/group.ejs:14
    12|                 let itemModel = { model: item, settings: settings, Utils: Utils};
    13|             %>
 >> 14|                 <%- include(partialFile, itemModel ) %>
    15|             <% }
    16|         } %>
    17|     </div>

/app/views/partials/dashboard/app.ejs:1
 >> 1| <% 
    2|     let app = AppHelper.get(model.AppName);
    3|     let target = settings.LinkTarget ?? '_self';
    4|     let title = model.Name ?? model.AppName;

Cannot read properties of undefined (reading 'Interval')
    at eval ("/app/views/partials/dashboard/app.ejs":14:24)
    at app (/app/node_modules/ejs/lib/ejs.js:692:17)
    at include (/app/node_modules/ejs/lib/ejs.js:690:39)
    at eval ("/app/views/partials/dashboard/group.ejs":34:17)
    at group (/app/node_modules/ejs/lib/ejs.js:692:17)
    at include (/app/node_modules/ejs/lib/ejs.js:690:39)
    at eval ("/app/views/home.ejs":51:17)
    at home (/app/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/app/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/app/node_modules/ejs/lib/ejs.js:489:10)

**Comment by revenz** [comment]
you dont happen to have adguardhome configured?

**Comment by revenz** [comment]
i just pushed "0.3.0.178" which should fix this.    adguardhome was renamed to AdGuard Home.   so if you edit that app it probably wont be found, but it wont crash.  just edit it and update it.
Let me know if that fixes it.

**Comment by ExXxtr3me2** [comment]
That worked, thank you.
But now my page looks very strange:

![image](https://user-images.githubusercontent.com/82820885/156127663-d74ff8e0-c47f-4dc2-80f7-0ac7419e3a4e.png)

**Comment by ExXxtr3me2** [comment]
Default view is working, but custom icons are not showing.

**Comment by revenz** [comment]
just uploaded 0.3.0.180 which fixes the other themes.  if the icons are still broken in 0.3.0.180 can you try re-adding them?  and also is your /wwwroot/images directory mapped outside of the docker image?  (this is done by default on unRAID)

**Comment by ExXxtr3me2** [comment]
The updates fixed the view, but the icons are still missing.
Yes the images are mapped outside, i´m using unRAID.

**Comment by revenz** [comment]
I just tried adding both a custom icon for an app (FileFlows) and for a link on the latest unraid image.  both worked for me in all themes.

I'm going to need the log from the app in unRAID.    just refresh the page then post the log.   the console log from the browser F12 for devtools see if there's any errors.    

can you check if the images appear in your appdata/fenrus/images/icons directory?
![image](https://user-images.githubusercontent.com/958400/156136351-5044376d-ac35-440a-a936-d49291d6665c.png)

icons are not saved as part of the config files, they're saved outside of it in the appdata/fenrus/images/icons directory so I cant just use your config file and test, cos they will be blank/missing.

also what apps/links are you setting custom icons on?   just incase that makes any difference.  If I can repo it I can fix it.

**Comment by ExXxtr3me2** [comment]
I deleted the apps and readded them, now the icons are working. 👍
Thanks for your quick help.

**Comment by revenz** [comment]
glad you got it working
